


name: 'Clear Token'
description: 'This will allow to use a Github token when jobs are triggered on pull requests from forks. This will obfuscate the key, Github will not complain that the key is in clear in the repo.'
inputs:
  bot_token_encrypted:
    description: The token encrypted using xor
    required: true
  bot_token_xor_key:
    description: The xor key
    required: true
outputs:
  token:
    description: The clear token in output
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: key
  color: green
