


name: 'Clear Token'
description: 'Decrypt a key using xor. This will allow to use a Github token when jobs are triggered on pull requests from forks.'
inputs:
  bot_token_encrypted:
    description: The token encrypted using xor
    required: true
  bot_token_xor_key:
    description: The xor key
    required: true
outputs:
  token:
    description: The clear token in output
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: briefcase
  color: green
