

on:
  pull_request:
    types:
      - labeled
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: opengisch/qgis-docbot@v1.0.1
      with:
        repo_slug: qgis/QGIS-Documentation
        bot_username: qgis-bot
        bot_token: ddbdec32940df79f1adf2369b4b10f10b5a66f65
        bot_token_key: a1b2c3d47311f8e29e204f85a81b4df4a44e252c
        github_token: ${{ secrets.GITHUB_TOKEN }}