
name: Test PR label to issue

on:
  pull_request:
    types:
      - closed

jobs:
  docbot:
    runs-on: ubuntu-latest
    name: Create issue on doc repo for labeled issue
    if: github.event.pull_request.merged == 'merged' && contains('documentation', github.event.pull_request.labels)
    steps:
      - name: Clear GH Token
        id: token
        uses: opengisch/clear-token@v1.0.12
        with:
          bot_token_encrypted: ddbdec32940df79f1adf2369b4b10f10b5a66f65
          bot_token_xor_key: a1b2c3d47311f8e29e204f85a81b4df4a44e252c
      - name: Create Documentation issue
        id: doc_issue
        uses: maxkomarychev/oction-create-issue@v0.7.1
        with:
          token: ${{ steps.token.outputs.token }}
          owner: qgis
          repo: QGIS-Documentation
          title: ${{ format('Request in QGIS ({1})', github.event.pull_request.number, github.event.pull_request.title) }}
          body: ${{ format('Request for documentation in QGIS/qgis#{0} {1})', github.event.pull_request.number, github.event.pull_request.title) }}
      - name: Print outputs
        run: |
          echo ${{ steps.doc_issue.outputs.id }}
          echo ${{ steps.doc_issue.outputs.number }}

