

on:
  pull_request:
    types:
      - labeled
jobs:
  docbot:
    runs-on: ubuntu-latest
    name: Create issue on doc repo for labeled issue
    steps:
      - name: Dump GitHub context
        env:
          label: ${{ github.event.label.name }}
          pr-title: ${{ github.event.pull_request.head.title }}
          context: ${{ toJson(github) }}
        run: echo "$context"
      - name: Get PR info
        if: github.event.label.name == 'duplicate'
        id: hello
        uses: opengisch/qgis-docbot@v1.0.7
        with:
          repo_slug: qgis/QGIS-Documentation
          bot_username: qgis-bot
          bot_token: ddbdec32940df79f1adf2369b4b10f10b5a66f65
          bot_token_key: a1b2c3d47311f8e29e204f85a81b4df4a44e252c
          github_token: ${{ secrets.GITHUB_TOKEN }}