

on:
  pull_request:
    types:
      - labeled
jobs:
  docbot:
    runs-on: ubuntu-latest
    name: Create issue on doc repo for labeled issue
    steps:
      - name: Dump GitHub context
        env:
          label: ${{ github.event.label.name }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_number: ${{ github.event.pull_request.number }}
          context: ${{ toJson(github) }}
        run: echo "$pr_title"
      - name: Create Documentation issue
        uses: maxkomarychev/oction-create-issue@v0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{'Request for documentation on QGIS/qgis#'+${{ github.event.pull_request.number }}+' ('+github.event.pull_request.title+')'}}
      - name: Print outputs
        run: |
          echo ${{ steps.my_step_id.outputs.id }}
          echo ${{ steps.my_step_id.outputs.number }}
      - name: Get PR info
        if: github.event.label.name == 'duplicate'
        id: hello
        uses: opengisch/qgis-docbot@v1.0.7
        with:
          repo_slug: qgis/QGIS-Documentation
          bot_username: qgis-bot
          bot_token: ddbdec32940df79f1adf2369b4b10f10b5a66f65
          bot_token_key: a1b2c3d47311f8e29e204f85a81b4df4a44e252c
          github_token: ${{ secrets.GITHUB_TOKEN }}